### ISSUE TITLE
如何学习pyqt？

### ISSUE THREAD

**Issue by wplct** [CoderUnion/coderunion-github-talk#55]
有什么资料么

**Comment by SimplyY** [comment]
看到了，放学后(晚上了吧)，我来写写zhihurss的项目制作过程吧

**Comment by SimplyY** [comment]
## zhihurss 的制作过程

### 起因
看到7s 的 https://github.com/7sDream/zhihu-py3 知乎爬虫库，然后用 python 爬了偶像的回答，于是就做了一个客户端。

### 技术选型

qml（写界面） + pyqt + python + zhihu-py3

### 编写过程
pyqt 很像 qt 的，大部分的类啊什么的 都是模仿 qt c++ 的。

qml 我是看这个的 http://blog.csdn.net/foruok/article/details/28620525 一篇一篇的看，最关键的是这一篇  http://blog.csdn.net/foruok/article/details/32698603

pyqt 有这个 http://python.jobbole.com/81276/


### 最关键的

当把一些基本的知识弄懂后，做项目的时候，最关键的就是谷歌了，先想好自己要完成什么，然后去找相关的资料，或者请教一下大牛。

当时我开发了20+天，谷歌了十来天吧，虽然确实效率低，因为自己基础不牢，很多东西不懂。不过经过这20+天，谷歌能力加强不少，后期基本上能快速精确定位答案，这个能力真的很重要，值得训练。

**Comment by wplct** [comment]
要安装qt么，5g大小觉得好奇怪

**Comment by SimplyY** [comment]
我装了，主要是写 qml，还有设计ui

**Comment by disoul** [comment]
毕竟底层api都是一样的，先看看c++的文档吧，比py的全很多
