### ISSUE TITLE
issues是啥？

### ISSUE THREAD

**Issue by fflamingogo** [CoderUnion/coderunion-github-talk#57]
那就试试看咯

**Comment by SimplyY** [comment]
就不太多文字介绍了，就是点点点什么的，下面图上面。

> 然后 issue 是任何github user都可以 new issue comment 的， 不过别人的 comment 的内容可以被 owner 删除 修改，目前我就知道这些。

![image](https://cloud.githubusercontent.com/assets/8455579/9962175/01e6fc42-5e57-11e5-89ec-a51343980a32.png)

![image](https://cloud.githubusercontent.com/assets/8455579/9962183/0ca43ab4-5e57-11e5-9078-9c90d49deab1.png)

![image](https://cloud.githubusercontent.com/assets/8455579/9962194/151d711a-5e57-11e5-924e-8df599d30fdb.png)

**Comment by fflamingogo** [comment]
3Q,我明白了

**Comment by SimplyY** [comment]
应该的啊，我把这个 ref 到报道帖应该不少人不知道。。
