### ISSUE TITLE
有个远程仓库，我要创建一个分支，需要哪些流程？

### ISSUE THREAD

**Issue by fflamingogo** [CoderUnion/coderunion-github-talk#58]
需要fork吗?

**Comment by SimplyY** [comment]
我刚关电脑，还是应该截图方便说。。

@codefalling  蛇神来说说吧

**Comment by CodeFalling** [comment]
不打算截图详细说明，这也不符合我们的意图。

- `git branch`可以在本地创建分支

- `git checkout`可以切换到指定分支

- `git checkout -b`可以创建并切换到分支

- `git push origin xyz:haha`表示推送本地的`xyz`分支到远端`origin`的`haha`分支，若`haha`不存在则创建。

更多的用法可以通过搜索引擎自己搜索，推荐阅读《Pro Git》

**Comment by fflamingogo** [comment]
我不太明白的是，fork的意思是不是已经远程建了一个分支了，然后我把这个分支clone下来，对这个分支操作后，push到分支上，在github上可以合并？

**Comment by SimplyY** [comment]
我还以为是PR 之前看错了，，

**Comment by SimplyY** [comment]
#39  那搜git，有几个git的教程，git的原理需要好好了解一下，不然用的时候很多麻烦。

**Comment by fflamingogo** [comment]
好吧，公司今天突然svn转git，搭了个和github很像的站，明天开始要用了

**Comment by SimplyY** [comment]
话说我还是觉得是PR啊，，fork，，是PR的时候要用的，也就是对github上非自己的仓库进行操作，这个需要使用PR,如果是要做这个，建议再开一个如何PR的issue

**Comment by fflamingogo** [comment]
private  repository？我刚刚试了一下下，看来和我想象的不一样呀，项目属于组织，我fork一下后才可以clone下来

**Comment by SimplyY** [comment]
fork是github自带的操作，PR也是，svn转git蛮好的(虽然我没用过svn)但是git真心棒。

fork 是对别人的自己没写权限的仓库，在自己那创(实际上还是github上的远程仓库)建一个新的分支，然后新的分支就有写权限了，你对同时新的仓库的修改可以通过PR申请提交代码到原仓库。

如果是公司的话，你应该有写的权限的。

**Comment by SimplyY** [comment]
PR 是pull request 的缩写

**Comment by fflamingogo** [comment]
这么说来并不需要fork呀。。

**Comment by SimplyY** [comment]
公司忘记给你写的权限了吧，，按道理来说，公司即便是一个组织，也应该给写的权限。

当然不排除，提交代码通过PR的方式。PR来提交代码，确实是，先fork 再clone，到本地，再改代码并提交push，再PR

**Comment by SimplyY** [comment]
需不需要fork 取决于权限吧，我是这么理解的

**Comment by fflamingogo** [comment]
哦，明白了，我还以为一定要先fork，这样的话，我可以本地创建分支，不需要fork了
