### ISSUE TITLE
jser交流贴

### ISSUE THREAD

**Issue by SimplyY** [CoderUnion/coderunion-github-talk#59]
jser web 前端 后端 以后更有react native 。node 大法好，一起在这报道一下，认识一下，以后可以直接开issue分享知识，交流知识，甚至合作开发(比如一个人写库，另一个人来用)

**Comment by GargouillePao** [comment]
报道，是这样么。。。

**Comment by SimplyY** [comment]
嗯，这样就行，先报个道，以后就在这里分享知识交流技术⊙▽⊙

**Comment by fflamingogo** [comment]
react native有机会要试试

**Comment by disoul** [comment]
最近在练习angular，目前正在做一个webapp，希望未来移动端`全球制霸`

**Comment by NaturalL** [comment]
嘿嘿，我也写了大半年js，node和前端

**Comment by SimplyY** [comment]
淘宝的npm工具 https://npm.taobao.org/
这个不错耶。

**Comment by SimplyY** [comment]
这个太牛逼了。。 https://github.com/lodash/lodash

**Comment by reverland** [comment]
os.js ......
nodeos .......
