### ISSUE TITLE
acm 和 做项目

### ISSUE THREAD

**Issue by SimplyY** [CoderUnion/coderunion-github-talk#60]
今日自创名句: 弄acm 类似于大吃敏捷书，做项目则是吃力量书，智力书(我该补补敏捷了)

ps:其实acm我接触不深，但是感觉非常训练反应能力，故揣测为敏捷

**Comment by xen0n** [comment]
羡慕你们记性好的，本叒估计也就一辈子google了囍

**Comment by SimplyY** [comment]
毛线记性好啊，，明明记性差，靠笔记辅助记记，气体你才是真奥义记性好，，

**Comment by CodeFalling** [comment]
人脑不适合精确记忆（好吧我说的是我脑）和上下文切换，基本借助大量的外部工具整理思路，记下思考的问题和收集资料。
推荐使用outline类的工具整理思路，效果奇佳。例如emacs orgmode，vim
org，workflowy，omnifocus，omnioutliner etc

Sent using CloudMagic [https://cloudmagic.com/k/d/mailapp?ct=pi&cv=7.3.25&pv=8.4.1]

**Comment by reverland** [comment]
> 羡慕你们记性好的，本叒估计也就一辈子google了囍

追随气体大神的谷歌之路，可惜连后背都看不清T T

**Comment by semprathlon** [comment]
一线作战人员表示：
在长期的训练（必然要吸收大量智力）以后转入比赛状态时，容易因为一些始料未及的赛况或灾难性的提交返回结果而受挫；
个人认为`压力下编程`所需的素质（偏指毅力、抗打击性）至少与敏捷同等重要。
还有别忘了这是个团队比赛……

**Comment by semprathlon** [comment]
其实凭着毅力、敏捷以及受打击后的恢复力就足以压制对手了，智商碾压措施是用来主宰战场的。

**Comment by semprathlon** [comment]
事实证明：在Codercup(北京)赛场上，我队解出3题时已推进到了第28名/共72队，敏捷度可算达标；但后续难题较难攻破，耐力不足以续航，最终4题第40名/72队。
@SimplyY

**Comment by SimplyY** [comment]
看来智力哪都很重要。。
