### ISSUE TITLE
关于git alias的妙用，可以大大改善git log体验

### ISSUE THREAD

**Issue by SimplyY** [CoderUnion/coderunion-github-talk#61]
www.liaoxuefeng.com/wiki/0013739516305929606dd18361248578c67b8067c8c017b000/001375234012342f90be1fc4d81446c967bbdc19e7c03d3000 git lg大法好，比原来的git log好用太多

**Comment by xen0n** [comment]
[我dotfiles](https://github.com/xen0n/dotfiles)里有一些丧心病狂的alias来着

顺便这种alias一看就是用过svn的（手动斜眼笑

**Comment by CodeFalling** [comment]
fish shell用户推荐使用oh-my-fish的balias plugin替代alias，这样alias也将继承原命令的补全😉。

On 周一, 9月 21, 2015 at 9:23 上午, CoderUnion/coderunion-github-talk
<reply@reply.github.com>
wrote:

[http://www.liaoxuefeng.com/wiki/0013739516305929606dd18361248578c67b8067c8c017b000/001375234012342f90be1fc4d81446c967bbdc19e7c03d3000] 
www.liaoxuefeng.com/wiki/0013739516305929606dd18361248578c67b8067c8c017b000/001375234012342f90be1fc4d81446c967bbdc19e7c03d3000
[http://www.liaoxuefeng.com/wiki/0013739516305929606dd18361248578c67b8067c8c017b000/001375234012342f90be1fc4d81446c967bbdc19e7c03d3000] git lg大法好，比原来的git log好用太多

—
Reply to this email directly or view it on GitHub
[https://github.com/CoderUnion/coderunion-github-talk/issues/61] .[https://github.com/notifications/beacon/AFL1IAeh4p9bEtyzJp8iDT1d-xQ2ktT_ks5oz1OagaJpZM4GAm3i.gif]

**Comment by CodeFalling** [comment]
打算删掉引用结果只删掉一部分，，然后就成了很奇怪的样子，，看来是应该找个好用的github iOS客户端了，，

**Comment by xen0n** [comment]
@CodeFalling 看来是应该找个好用的移动操作系统了（手动贴吧开心

**Comment by SimplyY** [comment]
@codefalling  我直接用手机版github的网页，觉得很不错

**Comment by xen0n** [comment]
@SimplyY +1

**Comment by CodeFalling** [comment]
修改issue需要进桌面版本
@codefalling [https://github.com/codefalling] 我直接用手机版github的网页，觉得很不错

—
Reply to this email directly or view it on GitHub
[https://github.com/CoderUnion/coderunion-github-talk/issues/61#issuecomment-141861760] .[https://github.com/notifications/beacon/AFL1IMPkVSduiKEvPUdVoI-Tl6Mi9sXJks5oz2K2gaJpZM4GAm3i.gif]

**Comment by SimplyY** [comment]
@codefalling  那不一样同一个页面完成嘛，很舒服呀，就点一下右下角

**Comment by CodeFalling** [comment]
@SimplyY 在手机上访问电脑版页面一点都不「舒服」，（尤其是Safari这种都不想打开的浏览器

**Comment by SimplyY** [comment]
@codefalling chrome大法好，

**Comment by RMasamune** [comment]
codehub


在2015年09月21日 10:39，She Jinxin 写道:
@SimplyY 在手机上访问电脑版页面一点都不「舒服」，（尤其是Safari这种都不想打开的浏览器

**Comment by CodeFalling** [comment]
@SimplyY iOS下的chrome是残废的，但是又有很多好（付费）应用。

我正在找看看有没有便宜的Github客户端，貌似最便宜的的确是CodeHub（Pro 12块）。暂时先缓缓说不定以后自己写个呢😂。

**Comment by semprathlon** [comment]
看了以上，顿时觉得重回手机党木有人权的年代；
TODO列表因此又多了一项
