### ISSUE TITLE
江大编程开源图书馆正式成立

### ISSUE THREAD

**Issue by SimplyY** [CoderUnion/coderunion-github-talk#67]
仓库 in here

https://github.com/CoderUnion/jn-code-library

有兴趣的江大在校生赶紧看过来~

**Comment by reverland** [comment]
O.O 电子书打印也挺好，江浙沪包邮哈哈哈

**Comment by NaturalL** [comment]
哇，不错，可以用闲置的书，换别人的书看，资源合理配置好啊
