### ISSUE TITLE
关于coderunion教程的设想

### ISSUE THREAD

**Issue by SimplyY** [CoderUnion/coderunion-github-talk#74]
我们可以弄一个大的学习教程项目，就叫 《coderunicon 编程学习教程》 好了，教程设想初步如图

![image](https://cloud.githubusercontent.com/assets/8455579/12062135/e7e79c94-afd1-11e5-897d-d89c4ec8a6e7.png)

**Comment by SimplyY** [comment]
移步 https://github.com/CoderUnion/coderunion-code-tutorial/issues/1

**Comment by reverland** [comment]
你们又想搞个大新闻233

**Comment by reverland** [comment]
教程这种东西确实能够聚拢人，虽然个人没大兴致。。。

**Comment by SimplyY** [comment]
不算发新闻呀，只是想造福一下新一届的学弟学妹们，和增加自身在 github 的学习和交流

**Comment by SimplyY** [comment]
然而。。。没后文了

不过我最近在写一个前端教程， https://github.com/SimplyY/web-front-end-thinking-tutorial
