### ISSUE TITLE
分享一个 RESTful API 设计规范

### ISSUE THREAD

**Issue by neo1218** [CoderUnion/coderunion-github-talk#78]
地址: https://github.com/BingyanStudio/share-and-standards/blob/master/RESTful-API-design-standards.md
这是华科冰岩团队总结的一个规范，感觉还不错，拿来给大家分享一下😄。

**Comment by SimplyY** [comment]
很不错，可读性很高，想当年我自己捣鼓 restful 到底是什么，知道自己写了才知道。。。
这个非常适合让不知道的人，在做项目之前轻松了解其概念，可以减少走弯路。
