### ISSUE TITLE
test

### ISSUE THREAD

**Issue by gy134340** [CoderUnion/coderunion-github-talk#80]
test

**Comment by neo1218** [comment]
test what?

**Comment by SimplyY** [comment]
233，test test 。

But I think test(or try) is very important to learn coding.

**Comment by gy134340** [comment]
can you  guys follow me

**Comment by gy134340** [comment]
I am sorry to say that , you guys are big cow

**Comment by xen0n** [comment]
> big cow
噗蛤蛤蛤蛤蛤

**Comment by reverland** [comment]
大母牛。。。

**Comment by gy134340** [comment]
我还以为母校计科已死，哈哈JU
