### ISSUE TITLE
MVC vs flux（redux）

### ISSUE THREAD

**Issue by SimplyY** [CoderUnion/coderunion-github-talk#81]
### MVC

以前的 MVC，模型与视图间可能存在的双向数据流动（省略了 C）：
- 比如 viewA、viewB 共享一个 modelA
- 在 viewA 里 change 了 modelA (数据流: viewA -> modelA)
- viewB 里要响应 modelA 的 change，也 change(数据流: modelA -> viewB)

于是乎这个时候MVVM 就出现了。但是数据流仍然是 **双向** 的。
### flux（redux）

而 flux 则重新发明了 MVC，将MVC 的双向数据流，变成单向数据流。

思考了几天，原来 flux 和 redux 其实就是，把 MVC 的 MC 层分成了三层：
- 一层是用来改变 M（即state） 的方法集合，在 redux 里为 reducer。数据流：  reducer -> store
- 还有一层则是 store。在 redux 里是，用来保存改变了的 state、state 改变后要调用的回调函数(listener)，这俩一起完成数据流 store -> view。
- 最后一层是 store 的 dispatch 方法分发的 action ，作为数据流的起点，去调用相应改变 state 的方法，(view or others' dispatch)action -> reducer。

也就是永远是 action -> reducer -> store -> view 的单向数据流。

**Comment by reverland** [comment]
膜
